name: experimint
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  redux: ">=2.0.0 <3.0.0"
  flutter_redux: ">=0.3.0 <0.4.0"
  fluro: ^1.3.1
  pigment: ^0.1.3
  flutter_parallax: ^0.1.1
  flutter_image: ^1.0.0
  async_loader: ^0.1.1
  image_picker: ^0.4.1
  google_sign_in: ^3.0.2
  firebase_analytics: ^0.3.3
  firebase_auth: ^0.5.5
  firebase_database: ^0.4.6
  firebase_storage: ^0.3.0
  flutter_gallery_assets: 0.1.4
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assets/Asics_Logo_1.png
   - assets/Asics_Logo_2.png
   - assets/Asics_Logo_3.png
   - assets/shoes/blue.png
   - assets/shoes/yellow.png
   - assets/shoes/red.png
   - packages/flutter_gallery_assets/products/backpack.png
   - packages/flutter_gallery_assets/products/belt.png
   - packages/flutter_gallery_assets/products/cup.png
   - packages/flutter_gallery_assets/products/deskset.png
   - packages/flutter_gallery_assets/products/dress.png
   - packages/flutter_gallery_assets/products/earrings.png
   - packages/flutter_gallery_assets/products/flatwear.png
   - packages/flutter_gallery_assets/products/hat.png
   - packages/flutter_gallery_assets/products/jacket.png
   - packages/flutter_gallery_assets/products/jumper.png
   - packages/flutter_gallery_assets/products/kitchen_quattro.png
   - packages/flutter_gallery_assets/products/napkins.png
   - packages/flutter_gallery_assets/products/planters.png
   - packages/flutter_gallery_assets/products/platter.png
   - packages/flutter_gallery_assets/products/scarf.png
   - packages/flutter_gallery_assets/products/shirt.png
   - packages/flutter_gallery_assets/products/sunnies.png
   - packages/flutter_gallery_assets/products/sweater.png
   - packages/flutter_gallery_assets/products/sweats.png
   - packages/flutter_gallery_assets/products/table.png
   - packages/flutter_gallery_assets/products/teaset.png
   - packages/flutter_gallery_assets/products/top.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
